package com.yangpa.fmate.model

import java.time.LocalDateTime

data class MatchCardData(
    val id: String,
    val title: String,
    val location: String,
    val scheduledAt: LocalDateTime,
    val level: String,
    val timeTag: String,
    val roleFocus: String,
    val surface: String,
    val capacity: Int,
    val joinedCount: Int,
    val hostType: String,
    val notes: String,
    val hostName: String,
    val hostRating: Double,
    val distanceKm: Double,
    val createdByUser: Boolean = false,
    val fee: Int = 12000,
    val reviewCount: Int = 24,
    val checkInCode: String = "FM-${id.takeLast(3).uppercase()}",
    val amenities: List<String> = emptyList(),
) {
    val tags: List<String>
        get() = listOf(timeTag, "$roleFocus 모집", surface, "${fee / 1000}천원")
}

data class PlayerProfile(
    val position: String,
    val skill: String,
    val timePreference: String,
)

enum class MatchFilter(val label: String) {
    All("전체"),
    Beginner("초급"),
    Intermediate("중급"),
    Night("야간"),
}

fun sampleMatches(now: LocalDateTime = LocalDateTime.now()): List<MatchCardData> {
    val baseDate = now.toLocalDate()

    return listOf(
        MatchCardData(
            id = "m1",
            title = "성수 수요 야간 5v5",
            location = "성수 서울숲 풋살파크",
            scheduledAt = baseDate.plusDays(2).atTime(20, 30),
            level = "중급",
            timeTag = "야간",
            roleFocus = "윙어",
            surface = "실내",
            capacity = 10,
            joinedCount = 7,
            hostType = "추천 매치",
            notes = "퇴근 후 바로 참여하는 직장인 중심 매치입니다. 패스 템포가 빠르고 분위기가 깔끔한 편입니다.",
            hostName = "TEAM Onion",
            hostRating = 4.9,
            distanceKm = 2.4,
            fee = 13000,
            reviewCount = 128,
            checkInCode = "FM-204",
            amenities = listOf("샤워실", "주차", "조끼"),
        ),
        MatchCardData(
            id = "m2",
            title = "건대 루프탑 목요전",
            location = "건대입구 루프탑 경기장",
            scheduledAt = baseDate.plusDays(3).atTime(20, 0),
            level = "중급",
            timeTag = "야간",
            roleFocus = "피보",
            surface = "실외",
            capacity = 12,
            joinedCount = 10,
            hostType = "인기 매치",
            notes = "혼자 와도 바로 팀 배정이 가능한 매치입니다. 현재 참가 중인 경기로 일정 탭에 표시됩니다.",
            hostName = "건대 FC",
            hostRating = 4.8,
            distanceKm = 3.1,
            fee = 15000,
            reviewCount = 87,
            checkInCode = "FM-728",
            amenities = listOf("루프탑", "대여화", "음료"),
        ),
        MatchCardData(
            id = "m3",
            title = "강남 토요 아침 풋살",
            location = "강남 탄천 풋살센터",
            scheduledAt = baseDate.plusDays(5).atTime(10, 0),
            level = "초급",
            timeTag = "주간",
            roleFocus = "수비",
            surface = "실외",
            capacity = 10,
            joinedCount = 6,
            hostType = "입문자 추천",
            notes = "가볍게 몸을 풀며 즐기는 초급자 중심 매치입니다. 풋살 입문자에게 맞는 템포입니다.",
            hostName = "Morning Kickers",
            hostRating = 4.7,
            distanceKm = 5.3,
            fee = 10000,
            reviewCount = 42,
            checkInCode = "FM-316",
            amenities = listOf("초보 환영", "주차", "락커"),
        ),
        MatchCardData(
            id = "m4",
            title = "마포 금요 경쟁전",
            location = "마포구민체육센터",
            scheduledAt = baseDate.plusDays(4).atTime(21, 0),
            level = "상급",
            timeTag = "야간",
            roleFocus = "골키퍼",
            surface = "실내",
            capacity = 10,
            joinedCount = 8,
            hostType = "도전 매치",
            notes = "강한 압박과 빠른 전환을 선호하는 상급자 중심 경기입니다.",
            hostName = "Mapo Rush",
            hostRating = 4.9,
            distanceKm = 4.6,
            fee = 14000,
            reviewCount = 65,
            checkInCode = "FM-920",
            amenities = listOf("실내", "기록 측정", "조끼"),
        ),
        MatchCardData(
            id = "m5",
            title = "서일대 캠퍼스 친선전",
            location = "서일대학교 운동장",
            scheduledAt = baseDate.plusDays(1).atTime(18, 30),
            level = "초급",
            timeTag = "야간",
            roleFocus = "윙어",
            surface = "실외",
            capacity = 12,
            joinedCount = 9,
            hostType = "학교 인증",
            notes = "서일대 학생 중심 친선 매치입니다. 신규 참가자도 바로 합류할 수 있도록 팀 밸런스를 맞춥니다.",
            hostName = "SeoIL Futsal",
            hostRating = 4.8,
            distanceKm = 0.6,
            fee = 8000,
            reviewCount = 53,
            checkInCode = "FM-SI1",
            amenities = listOf("학교 인증", "초보 환영", "무료 주차"),
        ),
        MatchCardData(
            id = "m6",
            title = "잠실 토요 리그 준비전",
            location = "잠실 종합운동장 풋살장",
            scheduledAt = baseDate.plusDays(6).atTime(16, 0),
            level = "상급",
            timeTag = "주간",
            roleFocus = "피보",
            surface = "실외",
            capacity = 10,
            joinedCount = 10,
            hostType = "모집 마감",
            notes = "리그 참가 전술 훈련을 겸한 상급자 매치입니다. 현재 정원이 모두 찼습니다.",
            hostName = "Jamsil League Lab",
            hostRating = 4.9,
            distanceKm = 6.8,
            fee = 16000,
            reviewCount = 112,
            checkInCode = "FM-JSL",
            amenities = listOf("전술 훈련", "영상 촬영", "심판"),
        ),
    )
}
